apiVersion: devices.kubeedge.io/v1alpha2
kind: DeviceModel
metadata:
  labels:
    description: 'My_ds18b20_with_python_in_rasberrypi'
    manufacturer: 'python'
  name: my-ds18b20-model
spec:
  properties:
  - name: temperature
    description: Temperature collected from the ds18b20.
    type:
      string:
        accessMode: ReadOnly
        defaultValue: '-1'
  - name: ping
    description: device awake
    type:
      string:
        accessMode: ReadOnly
        defaultValue: '-1'
  - name: message
    description: device message
    type:
      string:
        accessMode: ReadWrite
        defaultValue: 'default'
  - name: json
    description: JSON message
    type:
      string:
        accessMode: ReadWrite
        defaultValue: 'default'

